"""Phase 3 native NB-Polar public surface: field adapter, frozen transform, reference SC, tiny oracle, synthetic construction."""

from .adaptive_l1 import (
    FROZEN_K1_LEVELS as ADAPTIVE_L1_K1_LEVELS,
    FROZEN_PAIRS as ADAPTIVE_L1_PAIRS,
    FROZEN_SEEDS as ADAPTIVE_L1_FROZEN_SEEDS,
    PROTOCOL_NAME as ADAPTIVE_L1_PROTOCOL_NAME,
    run_paired_block as run_adaptive_l1_paired_block,
    run_adaptive_gate as run_adaptive_l1_gate,
)
from .algebra import make_gf2m, make_gf32, validate_symbols
from .construction import (
    BlockEvalResult,
    ConstructionResult,
    analytic_construction,
    analytic_order,
    build_construction,
    disclosure_order_from_stats,
    evaluate_blocks,
    failure_summary,
    genie_conditionals,
    resolvable_rank_corr,
    spearman_rank_corr,
    topk_overlap,
)
from .incremental import (
    ArmBlockResult as IncrementalArmResult,
    FROZEN_BLOCKS as P6_FROZEN_BLOCKS,
    FROZEN_K as P6_FROZEN_K,
    FROZEN_RUN_SEED as P6_FROZEN_RUN_SEED,
    NestedSchedule,
    PROTOCOL_NAME as INCREMENTAL_PROTOCOL_NAME,
    R1_BANNED_RUN_SEEDS as P6R1_BANNED_RUN_SEEDS,
    R1_FROZEN_BLOCKS as P6R1_FROZEN_BLOCKS,
    R1_PROTOCOL_NAME as P6R1_PROTOCOL_NAME,
    R1_RUN_SEED as P6R1_FROZEN_RUN_SEED,
    R1_TOEPLITZ_MASTER_SEED as P6R1_TOEPLITZ_MASTER_SEED,
    THREE_ARM_MODE as P6R1_MODE,
    TOEPLITZ_MASTER_SEED as P6_TOEPLITZ_MASTER_SEED,
    block_toeplitz_seed_bits as phase6_toeplitz_seed_bits,
    build_nested_schedule,
    recount_transcript as recount_incremental_transcript,
    rescue_comparison,
    run_incremental_block,
    run_incremental_r1_block,
    run_paired_dev_gate,
    run_static_comparator_block,
    run_three_arm_paired_dev_gate,
    validate_r1_run_seed as validate_phase6_r1_run_seed,
    validate_run_seed as validate_phase6_run_seed,
)
from .oracle import oracle_block_log_score, oracle_sc_metric
from .prior import (
    Conditioning,
    Provenance,
    SymbolMetric,
    build_p1_metrics,
    derive_p1,
    derive_p2,
    gather_p2_metrics,
    probs_to_symbol_metric,
    smooth_joint_to_conditional,
)
from .protocol import (
    BANNED_RUN_SEEDS,
    DEFAULT_K,
    DEFAULT_N,
    DEV_GATE_PER_BLOCK_SOFT_CAP_S,
    DEV_GATE_TOTAL_WALL_S,
    EPSILON,
    FROZEN_RUN_SEED,
    OUTCOMES,
    PROTOCOL_NAME,
    SEED_BITS,
    TAG_BITS,
    TOEPLITZ_MASTER_SEED,
    ProtocolRun,
    StaticBlockResult,
    block_toeplitz_seed_bits,
    execute_blocks,
    labels_from_symbols,
    labels_to_bits,
    recount_transcript,
    run_dev_gate,
    run_static_block,
    static_disclosure_coordinates,
    validate_run_seed,
    wilson_lower_bound,
)
from .sc import SCResult, sc_decode
from .synthetic import (
    DEV_SEED,
    EVAL_SEED,
    TRAIN_SEED,
    UNIT_SEED,
    analytic_erasure_probs,
    generate_erasure_block,
    generate_qsc_block,
)
from .transform import kernel_pair, polar_transform, polar_transform_reference, transform_and_select

__all__ = [
    "ADAPTIVE_L1_PROTOCOL_NAME",
    "ADAPTIVE_L1_FROZEN_SEEDS",
    "ADAPTIVE_L1_K1_LEVELS",
    "ADAPTIVE_L1_PAIRS",
    "run_adaptive_l1_gate",
    "run_adaptive_l1_paired_block",
    "make_gf2m",
    "make_gf32",
    "validate_symbols",
    "kernel_pair",
    "polar_transform",
    "polar_transform_reference",
    "transform_and_select",
    "sc_decode",
    "SCResult",
    "oracle_sc_metric",
    "oracle_block_log_score",
    "generate_erasure_block",
    "generate_qsc_block",
    "analytic_erasure_probs",
    "UNIT_SEED",
    "TRAIN_SEED",
    "DEV_SEED",
    "EVAL_SEED",
    "genie_conditionals",
    "disclosure_order_from_stats",
    "build_construction",
    "evaluate_blocks",
    "failure_summary",
    "resolvable_rank_corr",
    "analytic_construction",
    "spearman_rank_corr",
    "topk_overlap",
    "analytic_order",
    "ConstructionResult",
    "BlockEvalResult",
    "SymbolMetric",
    "Conditioning",
    "Provenance",
    "smooth_joint_to_conditional",
    "derive_p1",
    "derive_p2",
    "build_p1_metrics",
    "gather_p2_metrics",
    "probs_to_symbol_metric",
    "PROTOCOL_NAME",
    "DEFAULT_N",
    "DEFAULT_K",
    "EPSILON",
    "FROZEN_RUN_SEED",
    "TOEPLITZ_MASTER_SEED",
    "BANNED_RUN_SEEDS",
    "OUTCOMES",
    "TAG_BITS",
    "SEED_BITS",
    "DEV_GATE_TOTAL_WALL_S",
    "DEV_GATE_PER_BLOCK_SOFT_CAP_S",
    "StaticBlockResult",
    "ProtocolRun",
    "static_disclosure_coordinates",
    "labels_from_symbols",
    "labels_to_bits",
    "block_toeplitz_seed_bits",
    "wilson_lower_bound",
    "recount_transcript",
    "run_static_block",
    "execute_blocks",
    "run_dev_gate",
    "validate_run_seed",
    "INCREMENTAL_PROTOCOL_NAME",
    "P6_FROZEN_K",
    "P6_FROZEN_BLOCKS",
    "P6_FROZEN_RUN_SEED",
    "P6_TOEPLITZ_MASTER_SEED",
    "NestedSchedule",
    "IncrementalArmResult",
    "build_nested_schedule",
    "phase6_toeplitz_seed_bits",
    "run_incremental_block",
    "run_static_comparator_block",
    "run_paired_dev_gate",
    "recount_incremental_transcript",
    "validate_phase6_run_seed",
    "P6R1_MODE",
    "P6R1_PROTOCOL_NAME",
    "P6R1_FROZEN_BLOCKS",
    "P6R1_FROZEN_RUN_SEED",
    "P6R1_TOEPLITZ_MASTER_SEED",
    "P6R1_BANNED_RUN_SEEDS",
    "run_incremental_r1_block",
    "run_three_arm_paired_dev_gate",
    "rescue_comparison",
    "validate_phase6_r1_run_seed",
]
